'use strict'


angular.module('xin.pdf.recueil.traduction', [])
  .constant 'RECUEIL_TRAD',
    ALB:
      NUMERO_ETRANGER: "NR. I REGJ. PËR TË HUAJ"
      RECUEIL_N: "NR. I DOSJES"
      DATE_DEPOT_DEMANDE: "Data e dorëzimit të aplikimit"
      A_REMPLIR_PAR_PREFECTURE: "Për t’u plotësuar nga prefektura "
      PREMIERE_DEMANDE: "Aplikimi i 1-rë"
      REEXAMEN: "Rishqyrtim"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Të dhëna për gjendjen civile të aplikantit"
      NOM: "Mbiemri"
      PRENOMS: "Emri/at"
      NOM_USAGE: "-"
      F: "-"
      M: "-"
      DATE_NAISSANCE: "Datëlindja"
      LIEU_NAISSANCE: "Vendlindja (shteti dhe qyteti)"
      NATIONALITE: "Kombësia"
      NOM_PRENOM_PERE: "Mbiemri dhe emri i babait"
      NOM_PRENOM_MERE: "Mbiemri dhe emri i nënës"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Të dhëna për familjen e aplikantit"
      MARIE: "I/e martuar"
      CELIBATAIRE: "Beqar/e"
      VEUF: "I/e ve"
      DIVORCE: "I/e divorcuar"
      CONCUBIN: "Bashkëjetues/e"
      NOM_CONJOINT: "Mbiemri i bashkëshortit/es, nëse ka"
      PRENOM_CONJOINT: "Emri i bashkëshortit/es"
      NATIONALITE_CONJOINT: "Kombësia e bashkëshortit/es"
      DATE_LIEU_NAISSANCE_CONJOINT: "Data dhe vendi i lindjes së bashkëshortit/es"
      LIEU_RESIDENCE_CONJOINT: "Vendbanimi i tanishëm i bashkëshortit/es"
      NOMBRE_ENFANTS: "Numri i fëmijëve"
      DONT_ENTRES_EN_FRANCE: "nga të cilët gjenden në Francë"
      INDIQUER_TOUS_ENFANTS: "Jepni të dhëna për të gjithë fëmijët tuaj"
      NOM_ENFANT: "Mbiemri"
      PRENOM_ENFANT: "Emri"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Kombësia, datëlindja, vendlindja"
      LIEU_RESIDENCE_ACTUELLE: "Vendbanimi aktual"
      ADRESSE_COURRIER: "Adresa ku mund t’ju dërgojmë korrespondencë"
      CHEZ: "Merr"
      NUMERO_VOIE: "Nr"
      VOIE: "Rruga"
      CODE_POSTAL: "Kodi postar"
      VILLE: "Qyteti"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Të dhëna për mënyrën si keni hyrë në Francë dhe itinerarin që keni ndjekur që pasi u larguat nga vendi juaj i origjinës"
      DATE_DEPART_PAYS_ORIGINE: "Data e nisjes nga vendi i origjinës dhe/ose nga vendi prej të cilit erdhët në Francë"
      PAYS_TRAVERSES: "Vendi përmes të cilit kaluat"
      DATE_ENTREE: "Data e mbërritjes"
      DATE_SORTIE: "Data e largimit"
      MOYENS_TRANSPORTS: "Mjetet e transportit"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Si e kaluat kufirin?(pikë kalimi e autorizuar, apo duke iu shmangur kontrolleve)"
      FRANCE: "Francë"
      LANGUES: "Gjuha/ët që kuptoni"
      FAIT_LE: "Kryer më "
      PREFECTURE_DE: "Në prefekturën e"
      SIGNATURE: "NËNSHKRIMI"

    ENG:
      NUMERO_ETRANGER: "ALIEN REGISTRATION N°"
      RECUEIL_N: "File N°"
      DATE_DEPOT_DEMANDE: "Date of application"
      A_REMPLIR_PAR_PREFECTURE: "To be filled in by the prefecture"
      PREMIERE_DEMANDE: "1st application"
      REEXAMEN: "Re-consideration"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Information about the applicant's civil status"
      NOM: "Family name at birth"
      PRENOMS: "Given name"
      NOM_USAGE: "Family name"
      F: "F"
      M: "M"
      DATE_NAISSANCE: "Date of birth"
      LIEU_NAISSANCE: "Place of birth (country and town)"
      NATIONALITE: "Nationality"
      NOM_PRENOM_PERE: "Family name and given name of father"
      NOM_PRENOM_MERE: "Family name and given name of mother"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Information about the applicant's family"
      MARIE: "Married"
      CELIBATAIRE: "Single"
      VEUF: "Widow(er)"
      DIVORCE: "Divorced"
      CONCUBIN: "Cohabitee"
      NOM_CONJOINT: "Family name of partner, if applicable"
      PRENOM_CONJOINT: "Given name of partner"
      NATIONALITE_CONJOINT: "Partner’s nationality"
      DATE_LIEU_NAISSANCE_CONJOINT: "Partner’s date and place of birth"
      LIEU_RESIDENCE_CONJOINT: "Partner’s current place of residence"
      NOMBRE_ENFANTS: "Number of children"
      DONT_ENTRES_EN_FRANCE: "Number of children in France"
      INDIQUER_TOUS_ENFANTS: "Give details of all your children"
      NOM_ENFANT: "Family name"
      PRENOM_ENFANT: "Given name"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Nationality, date and place of birth"
      LIEU_RESIDENCE_ACTUELLE: "Current place of residence"
      ADRESSE_COURRIER: "Address where letters can be sent to you"
      CHEZ: "Care of"
      NUMERO_VOIE: "N°"
      VOIE: "Street"
      CODE_POSTAL: "Post code"
      VILLE: "Town"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Information on how you entered France and your itinerary since you left your country of origin"
      DATE_DEPART_PAYS_ORIGINE: "Date of departure from country of origin and/or country you left to come to France"
      PAYS_TRAVERSES: "Country travelled through"
      DATE_ENTREE: "Arrival date"
      DATE_SORTIE: "Departure date"
      MOYENS_TRANSPORTS: "Means of transport used"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "How did you cross the border?(official crossing point or clandestine crossing)"
      FRANCE: "France"
      LANGUES: "Language(s) understood"
      FAIT_LE: "Done on"
      PREFECTURE_DE: "At the prefecture of"
      SIGNATURE: "SIGNATURE"

    ARA:
      NUMERO_ETRANGER: "رقم تسجيل الأجنبي"
      RECUEIL_N: "رقم الملف"
      DATE_DEPOT_DEMANDE: "تاريخ تقديم الطلب"
      A_REMPLIR_PAR_PREFECTURE: "يُملأ من طرف أعوان المحافظة"
      PREMIERE_DEMANDE: "الطلب الأوّل"
      REEXAMEN: "طلب يُنظر فيه من جديد"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "معلومات عن الحالة المدنية لمقدّم الطلب"
      NOM: "اللقب/اسم العائلة"
      PRENOMS: "الاسم (الأسماء)"
      NOM_USAGE: "-"
      F: "أ"
      M: "ذ"
      DATE_NAISSANCE: "تاريخ الولادة"
      LIEU_NAISSANCE: "مكان الولادة (البلد والمدينة)"
      NATIONALITE: "الجنسية"
      NOM_PRENOM_PERE: "لقب الأب واسمه"
      NOM_PRENOM_MERE: "لقب الأم واسمها"
      INFORMATIONS_FAMILLE_DEMANDEUR: "معلومات عن عائلة مقدّم الطلب"
      MARIE: "متزوّج (ة)"
      CELIBATAIRE: "أعزب (عزباء)"
      VEUF: "أرمل (ة)"
      DIVORCE: "مطلّق (ة)"
      CONCUBIN: "عشير (ة)"
      NOM_CONJOINT: "لقب الشريك، عند الاقتضاء"
      PRENOM_CONJOINT: "اسم الشريك"
      NATIONALITE_CONJOINT: "جنسية الشريك"
      DATE_LIEU_NAISSANCE_CONJOINT: "تاريخ ومكان ولادة الشريك"
      LIEU_RESIDENCE_CONJOINT: "محل الإقامة الراهنة للشريك"
      NOMBRE_ENFANTS: "عدد الأطفال"
      DONT_ENTRES_EN_FRANCE: "عدد الأطفال الذين دخلوا إلى فرنسا"
      INDIQUER_TOUS_ENFANTS: "أعط اسماء جميع الأطفال"
      NOM_ENFANT: "اسم العائلة"
      PRENOM_ENFANT: "الاسم"
      NATIONALITE_DATE_LIEU_NAISSANCE: "الجنسية وتاريخ ومكان الولادة"
      LIEU_RESIDENCE_ACTUELLE: "مكان الإقامة الحالية"
      ADRESSE_COURRIER: "العنوان الذي تُرسَل إليه الرسائل"
      CHEZ: "عند"
      NUMERO_VOIE: "الرقم"
      VOIE: "الشارع"
      CODE_POSTAL: "الرمز البريدي"
      VILLE: "المدينة "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "معلومات عن طريقة دخولك إلى فرنسا ومسار رحلتك من البلد الأصلي"
      DATE_DEPART_PAYS_ORIGINE: "تاريخ المغادرة من البلد الأصلي و/أو البلد الذي قدِمت منه إلى فرنسا "
      PAYS_TRAVERSES: "بلدان العبور"
      DATE_ENTREE: "تاريخ الوصول إلى فرنسا"
      DATE_SORTIE: "تاريخ المغادرة"
      MOYENS_TRANSPORTS: "وسائل النقل المستخدمة"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "كيف خرجت من الحدود (نقطة عبور رسمية أو خروج عن طريق تفادي نقاط المراقبة)"
      FRANCE: "فرنسا"
      LANGUES: "اللغة (اللغات) التي أفهمها"
      FAIT_LE: "حرر في"
      PREFECTURE_DE: "في محافظة "
      SIGNATURE: "التوقيع"

    ARM:
      NUMERO_ETRANGER: "ՕՏԱՐԵՐԿՐԱՑՈՒ ԳՐԱՆՑԱՀԱՄԱՐ  N°"
      RECUEIL_N: "ԳՈՐԾ  N°"
      DATE_DEPOT_DEMANDE: "Դիմումի տրման ամսաթիվ՝"
      A_REMPLIR_PAR_PREFECTURE: "Լրացվում է պրեֆեկտուրայի (թաղապետարանի) կողմից"
      PREMIERE_DEMANDE: "Առաջին դիմում"
      REEXAMEN: "Վերանայում"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Տեղեկություններ դիմողի քաղաքացիական կացության վերաբերյալ "
      NOM: "Ազգանուն՝"
      PRENOMS: "Անուն (ներ)՝"
      NOM_USAGE: "-"
      F: "Ի"
      M: "Ա"
      DATE_NAISSANCE: "Ծննդյան ամսաթիվ՝ "
      LIEU_NAISSANCE: "Ծննդավայր  (երկիր և քաղաք)՝"
      NATIONALITE: "Քաղաքացիություն՝"
      NOM_PRENOM_PERE: "Հոր ազգանուն և անուն՝"
      NOM_PRENOM_MERE: "Մոր ազգանուն և անուն՝"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Տեղեկություններ դիմողի ընտանիքի վերաբերյալ"
      MARIE: "Ամուսնացած"
      CELIBATAIRE: "Ամուրի"
      VEUF: "Այրի"
      DIVORCE: "Ամուսնալուծված"
      CONCUBIN: "Համատեղ բնակվող (կողակից)"
      NOM_CONJOINT: "Ամուսնու (կնոջ )ազգանունը, առկայության դեպքում՝"
      PRENOM_CONJOINT: "Ամուսնու (կնոջ) անունը՝"
      NATIONALITE_CONJOINT: "Ամուսնու (կնոջ ) քաղաքացիությունը՝"
      DATE_LIEU_NAISSANCE_CONJOINT: "Ամուսնու (կնոջ)ծննդյան ամսաթիվը և վայրը՝ "
      LIEU_RESIDENCE_CONJOINT: "Ամուսնու (կնոջ) ներկայիս բնակության վայրը՝"
      NOMBRE_ENFANTS: "Երեխաների քանակը"
      DONT_ENTRES_EN_FRANCE: "որոնցից Ֆրանսիայում են՝"
      INDIQUER_TOUS_ENFANTS: "Նշել բոլոր երեխաներին"
      NOM_ENFANT: "Ազգանուն"
      PRENOM_ENFANT: "Անուն"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Քաղաքացիություն, ծննդյան ամսաթիվ և վայր"
      LIEU_RESIDENCE_ACTUELLE: "Ներկայիս բնակության վայր"
      ADRESSE_COURRIER: "Հասցե, որով կարելի է Ձեզ նամակներ առաքել"
      CHEZ: "Ու՞մ տանը՝"
      NUMERO_VOIE: "N° "
      VOIE: "Փողոց՝"
      CODE_POSTAL: "Փոստային ինդեքս՝ "
      VILLE: "Քաղաք "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Տեղեկություններ Ֆրանսիա մուտք գործելու պայմանների և ճամփորդական երթուղիների մասին սկսած մեկնման երկրից"
      DATE_DEPART_PAYS_ORIGINE: "Մեկնման երկրից և/կամ բնակության երկրից մեկնելու ամսաթիվը՝ "
      PAYS_TRAVERSES: "Որ երկրներով եք անցել"
      DATE_ENTREE: "Մուտքի ամսաթիվը"
      DATE_SORTIE: "Մեկնման ամսաթիվը"
      MOYENS_TRANSPORTS: "Տրանսպորտային միջոցներ"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Ինչպե՞ս եք հատել սահմանները (թույլատրված անցակետով կամ խուսափելով ստուգումներից)"
      FRANCE: "Ֆրանսիա"
      LANGUES: "Ի՞նչ լեզու(ներ) եք հասկանում՝"
      FAIT_LE: "Ամսաթիվ՝"
      PREFECTURE_DE: "Պրեֆեկտուրա՝"
      SIGNATURE: "Ստորագրություն"

    BEN:
      NUMERO_ETRANGER: "biHragt inbÆÁn n„ "
      RECUEIL_N: "niT n„ "
      DATE_DEPOT_DEMANDE: "Vebdenr tairK"
      A_REMPLIR_PAR_PREFECTURE: "ŸpãePktur  pUrN kreb"
      PREMIERE_DEMANDE: "1m Vebdn"
      REEXAMEN: "punW ibebcna"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "VebdnkarIr bYi¹¡gt tTYablI "
      NOM: "b„SsUck nam (pdbI) "
      PRENOMS: "Bal nam "
      NOM_USAGE: "-"
      F: "miHla"
      M: "pur›x"
      DATE_NAISSANCE: "jnMtairK"
      LIEU_NAISSANCE: "jnMóùan (ŸdS …b„ SHr) "
      NATIONALITE: "jatIyta "
      NOM_PRENOM_PERE: "iptar b„SsUck nam …b„ Bal nam "
      NOM_PRENOM_MERE: "matar b„SsUck nam …b„ Bal nam "
      INFORMATIONS_FAMILLE_DEMANDEUR: "VebdnkarIr pairbairk tTYablI "
      MARIE: "ibbaiHt"
      CELIBATAIRE: "AibbaiHt"
      VEUF: "ibptþIk (ibDba)"
      DIVORCE: "talakpãaÐ"
      CONCUBIN: "AibbaiHt saTI "
      NOM_CONJOINT: "pãeZajY Hel saTIr b„SsUck nam "
      PRENOM_CONJOINT: "saTIr Bal nam "
      NATIONALITE_CONJOINT: "saTIr jatIyta "
      DATE_LIEU_NAISSANCE_CONJOINT: "saTIr jnMtairK …b„ óùan "
      LIEU_RESIDENCE_CONJOINT: "saTIr bàtman basóùan "
      NOMBRE_ENFANTS: "sÇ»an s„KYa "
      DONT_ENTRES_EN_FRANCE: "ÒaeÆs sÇ»an s„KYa "
      INDIQUER_TOUS_ENFANTS: "Vpnar sb sÇ»anedr ibbrN idn"
      NOM_ENFANT: "b„SsUck nam (pdbI)"
      PRENOM_ENFANT: "Bal nam"
      NATIONALITE_DATE_LIEU_NAISSANCE: "jatIyta, jnMtairK …b„ óùan"
      LIEU_RESIDENCE_ACTUELLE: "বসবাসের বর্তমান স্থান"
      ADRESSE_COURRIER: "ŸZ ifkanay Vpnaek icifpº pafaena sÝb"
      CHEZ: "pãZetþ "
      NUMERO_VOIE: "nÜr "
      VOIE: "raó»a "
      CODE_POSTAL: "Ÿpañekah "
      VILLE: "SHr"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "obD ATba AEbD Baeb …b„ injŸdS ŸTek ŸZ peT, ŸZ sb ZanbaHn bYbHar ker ÒaeÆs pãebS kereCn tar bàNna"
      DATE_DEPART_PAYS_ORIGINE: "ŸZ ŸdS ŸTek …eseCn, Ÿs ŸdS ATba injedS tYaegr tairKW"
      PAYS_TRAVERSES: "ŸZ sb ŸdS Aitº¡m ker …eseCn"
      DATE_ENTREE: "pãebeSr tairK "
      DATE_SORTIE: "tYaegr tairK "
      MOYENS_TRANSPORTS: "ŸZ sb ZanbaHn bYbHar kereCn"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "ik Baeb sImaÇ» Aitº¡m ker iCeln? (obD naik AEbD peT)"
      FRANCE: "ÒaÆs"
      LANGUES: "ŸZ (sb) Baxa buJet paern "
      FAIT_LE: "tairK"
      PREFECTURE_DE: "ŸpãePktur"
      SIGNATURE: "sÔaQr"

    CHI:
      NUMERO_ETRANGER: "外国人注册号"
      RECUEIL_N: "文件号"
      DATE_DEPOT_DEMANDE: "申请日期"
      A_REMPLIR_PAR_PREFECTURE: "由所在辖区填写"
      PREMIERE_DEMANDE: "首次申请"
      REEXAMEN: "复议"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "申请人公民身份信息"
      NOM: "姓"
      PRENOMS: "名"
      NOM_USAGE: "-"
      F: "女"
      M: "男"
      DATE_NAISSANCE: "出生日期"
      LIEU_NAISSANCE: " 出生地 (国家及城镇"
      NATIONALITE: "国籍"
      NOM_PRENOM_PERE: "父亲姓名"
      NOM_PRENOM_MERE: "母亲姓名"
      INFORMATIONS_FAMILLE_DEMANDEUR: "申请人家庭信息"
      MARIE: "已婚"
      CELIBATAIRE: "未婚"
      VEUF: "丧偶"
      DIVORCE: "离异"
      CONCUBIN: "同居"
      NOM_CONJOINT: "如有伴侣，他（她）的姓"
      PRENOM_CONJOINT: "伴侣的名字"
      NATIONALITE_CONJOINT: " 伴侣国籍"
      DATE_LIEU_NAISSANCE_CONJOINT: "伴侣的出生日期及出生地"
      LIEU_RESIDENCE_CONJOINT: "伴侣现居住地址"
      NOMBRE_ENFANTS: "子女人数"
      DONT_ENTRES_EN_FRANCE: "留法子女人数"
      INDIQUER_TOUS_ENFANTS: "子女信息"
      NOM_ENFANT: "姓"
      PRENOM_ENFANT: "名"
      NATIONALITE_DATE_LIEU_NAISSANCE: "国籍，出生日期及出生地"
      LIEU_RESIDENCE_ACTUELLE: "现居住地"
      ADRESSE_COURRIER: "收件地址"
      CHEZ: "转交"
      NUMERO_VOIE: "门牌号"
      VOIE: "街道"
      CODE_POSTAL: "邮编"
      VILLE: "城镇"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "入境法国及离开原属国后的路径信息"
      DATE_DEPART_PAYS_ORIGINE: "离开原属国和/或其他国家，动身前往法国的日期"
      PAYS_TRAVERSES: "经由国家"
      DATE_ENTREE: "到达日期"
      DATE_SORTIE: "离开日期"
      MOYENS_TRANSPORTS: "交通方式"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "如何越过边境? (官方关口或秘密越境)"
      FRANCE: "法国"
      LANGUES: "所会语言（一种或多种）"
      FAIT_LE: "日期"
      PREFECTURE_DE: "所在辖区"
      SIGNATURE: "签名"

    HAT:
      NUMERO_ETRANGER: "NIMEWO ETRANJ "
      RECUEIL_N: "NIMEWO DOSYE"
      DATE_DEPOT_DEMANDE: "Dat klasman dosye ki nan aplikasyon an"
      A_REMPLIR_PAR_PREFECTURE: "Prefecture ki pou ranpli pati sa"
      PREMIERE_DEMANDE: "Premye aplikasyon"
      REEXAMEN: "Revize"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Enfòmasyon konsènan estati sivil aplikan an"
      NOM: "Siyati"
      PRENOMS: "Non"
      NOM_USAGE: "-"
      F: "-"
      M: "-"
      DATE_NAISSANCE: "Dat ou fèt"
      LIEU_NAISSANCE: "Kote ou fèt (peyi ak vil)"
      NATIONALITE: "Moun ki peyi"
      NOM_PRENOM_PERE: "Siyati epi non papa"
      NOM_PRENOM_MERE: "Siyati épi non manman"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Enfòmasyon konsènan fanmi aplikan an"
      MARIE: "Marye"
      CELIBATAIRE: "selibatè"
      VEUF: "Vèf (vèv)"
      DIVORCE: "Divòse"
      CONCUBIN: "moun nan kay"
      NOM_CONJOINT: "Siyati mari oswa madanm siw genyen"
      PRENOM_CONJOINT: "Non mari oswa madanm"
      NATIONALITE_CONJOINT: "Nasyonalite nan mari oswa madanm nan"
      DATE_LIEU_NAISSANCE_CONJOINT: "Dat ak koté li fèt nan mari oswa madanm nan"
      LIEU_RESIDENCE_CONJOINT: "Kouran kote rezidans nan mari oswa madanm nan"
      NOMBRE_ENFANTS: "Kantite timoun"
      DONT_ENTRES_EN_FRANCE: "Kite vinn an Frans"
      INDIQUER_TOUS_ENFANTS: "Idantifie tout timoun"
      NOM_ENFANT: "Siyati"
      PRENOM_ENFANT: "Non"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Nasyonalite, dat ak kote li fèt"
      LIEU_RESIDENCE_ACTUELLE: "Kouran kote rezidans"
      ADRESSE_COURRIER: "Adrès ou ka kontakte lapòs"
      CHEZ: "Kot kimoun"
      NUMERO_VOIE: "Nimewo"
      VOIE: "Adrès"
      CODE_POSTAL: "Kòd postal "
      VILLE: "Vil"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Enfòmasyon sou kondisyon sa ya nan antre nan Lafrans ak wout vwayaj nan peyi a ki gen origin"
      DATE_DEPART_PAYS_ORIGINE: "Dat depa soti nan peyi a ki gen origin ak/ oswa soti nan"
      PAYS_TRAVERSES: "Peyi travèse"
      DATE_ENTREE: "Dat antre"
      DATE_SORTIE: "Dat soti"
      MOYENS_TRANSPORTS: "Mwayen transpò"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Kondisyon pou travèse fwontyè (Crossing pwen oswa evite kontwòl)"
      FRANCE: "Frans"
      LANGUES: "Lang ou konprann"
      FAIT_LE: "Dat"
      PREFECTURE_DE: "Prefekti"
      SIGNATURE: "Siyati"

    SPA:
      NUMERO_ETRANGER: "Nº  REGISTRO DE EXTRANJEROS"
      RECUEIL_N: "N° EXPEDIENTE"
      DATE_DEPOT_DEMANDE: "Fecha de solicitud"
      A_REMPLIR_PAR_PREFECTURE: "A cumplimentar por la prefectura"
      PREMIERE_DEMANDE: "1ª solicitud"
      REEXAMEN: "Reconsideración"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Información sobre el estado civil del solicitante"
      NOM: "Apellido(s)"
      PRENOMS: "Nombre(s)"
      NOM_USAGE: "-"
      F: "-"
      M: "-"
      DATE_NAISSANCE: "Fecha de nacimiento"
      LIEU_NAISSANCE: "Lugar de nacimiento (país y ciudad)"
      NATIONALITE: "Nacionalidad"
      NOM_PRENOM_PERE: "Apellido(s) y nombre(s) del padre"
      NOM_PRENOM_MERE: "Apellido(s) y nombre(s) de la madre"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Información sobre la familia del solicitante"
      MARIE: "Casado/a"
      CELIBATAIRE: "Soltero/a"
      VEUF: "Viudo/a"
      DIVORCE: "Divorciado/a"
      CONCUBIN: "Pareja de hecho"
      NOM_CONJOINT: "Apellido(s) del cónyuge, si procede"
      PRENOM_CONJOINT: "Nombre(s) del cónyuge"
      NATIONALITE_CONJOINT: " Nacionalidad del cónyuge"
      DATE_LIEU_NAISSANCE_CONJOINT: "Fecha y lugar de nacimiento del cónyuge"
      LIEU_RESIDENCE_CONJOINT: "Lugar de residencia actual del cónyuge"
      NOMBRE_ENFANTS: "Número de hijos"
      DONT_ENTRES_EN_FRANCE: "Número de hijos que se encuentren en Francia"
      INDIQUER_TOUS_ENFANTS: "Indique los datos de todos sus hijos"
      NOM_ENFANT: "Apellido(s)"
      PRENOM_ENFANT: " Nombre(s)"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Nacionalidad, fecha y lugar de nacimiento "
      LIEU_RESIDENCE_ACTUELLE: "Nacionalidad, fecha y lugar de nacimiento "
      ADRESSE_COURRIER: "Dirección en la que se le puede contactar por correo postal"
      CHEZ: "A la atención de"
      NUMERO_VOIE: "N° "
      VOIE: "Calle "
      CODE_POSTAL: "Código postal"
      VILLE: "Ciudad"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Información sobre la entrada en Francia y el itinerario del viaje desde el país de origen"
      DATE_DEPART_PAYS_ORIGINE: "Fecha de salida del país de origen y/o país de procedencia"
      PAYS_TRAVERSES: "País de tránsito"
      DATE_ENTREE: "Fecha de entrada"
      DATE_SORTIE: "Fecha de salida"
      MOYENS_TRANSPORTS: "Medios de transporte empleados"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "¿Cómo cruzó la frontera? (puesto fronterizo autorizado o entrada clandestina)"
      FRANCE: "Francia"
      LANGUES: "Idioma(s) que comprende"
      FAIT_LE: "Dado el"
      PREFECTURE_DE: "En la prefectura de"
      SIGNATURE: "FIRMA"

    PER:
      NUMERO_ETRANGER: "تاریخ درخواست"
      RECUEIL_N: "شماره پرونده"
      DATE_DEPOT_DEMANDE: "شماره ثبت تبعه خارجی"
      A_REMPLIR_PAR_PREFECTURE: " باید توسط مقام ریاست پر شود "
      PREMIERE_DEMANDE: " درخواست اولیه"
      REEXAMEN: "بازنگری"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "اطلاعات مربوط به هويت متقاضی"
      NOM: "نام"
      PRENOMS: "نام خانوادگی"
      NOM_USAGE: "-"
      F: "مؤنث"
      M: "مذکر"
      DATE_NAISSANCE: "محل تولد (کشور و شهر)"
      LIEU_NAISSANCE: "تاريخ تولد"
      NATIONALITE: "تابعيت"
      NOM_PRENOM_PERE: "نام خانوادگی و نام پدر"
      NOM_PRENOM_MERE: "نام خانوادگی و نام مادر"
      INFORMATIONS_FAMILLE_DEMANDEUR: "اطلاعات مربوط به خانواده متقاضی"
      MARIE: "همزيست"
      CELIBATAIRE: "طلاق گرفته"
      VEUF: "بيوه"
      DIVORCE: "مجرد"
      CONCUBIN: "متأهل"
      NOM_CONJOINT: "  نام شريک جنسی"
      PRENOM_CONJOINT: "نام خانوادگی شريک جنسی، در صورت وجود"
      NATIONALITE_CONJOINT: "تابعيت شريک جنسی"
      DATE_LIEU_NAISSANCE_CONJOINT: "محل اقامت فعلی شريک جنسی"
      LIEU_RESIDENCE_CONJOINT: " تاريخ و محل تولد شريک جنسی"
      NOMBRE_ENFANTS: " تعداد فرزندان در فرانسه"
      DONT_ENTRES_EN_FRANCE: "تعداد فرزندان"
      INDIQUER_TOUS_ENFANTS: "مشخصات همه فرزندان خود را ارائه کنيد"
      NOM_ENFANT: "نام خانوادگی"
      PRENOM_ENFANT: "نام"
      NATIONALITE_DATE_LIEU_NAISSANCE: "تابعيت، تاريخ و محل تولد:"
      LIEU_RESIDENCE_ACTUELLE: "محل اقامت فعلی"
      ADRESSE_COURRIER: "نشانی برای فرستادن نامه"
      CHEZ: "برسد به دست"
      NUMERO_VOIE: "شماره "
      VOIE: "خیابان"
      CODE_POSTAL: "کد پستی"
      VILLE: " شهر"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "اطلاعات مربوط به چگونگی ورود به فرانسه و برنامه سفر شما پس از خروج از کشور مبداء"
      DATE_DEPART_PAYS_ORIGINE: "تاریخ خروج از کشور مبداء و/یا کشوری که از آنجا به سمت فرانسه حرکت کردید"
      PAYS_TRAVERSES: "کشوری که از آن عبور کردید"
      DATE_ENTREE: "تاریخ ورود"
      DATE_SORTIE: "تاریخ خروج"
      MOYENS_TRANSPORTS: "وسایل نقلیه استفاده شده برای سفر"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "چگونه از مرز عبور کردید؟ (عبور از مرز قانونی یا عبور مخفی)"
      FRANCE: "فرانسه"
      LANGUES: "آشنا با زبان(های)"
      FAIT_LE: "تاريخ"
      PREFECTURE_DE: "در ریاست"
      SIGNATURE: "امضا"

    GEO:
      NUMERO_ETRANGER: "უცხოელის რეგისტრაციის N"
      RECUEIL_N: "ფაილის  N"
      DATE_DEPOT_DEMANDE: "განაცხადის შევსების თარიღი"
      A_REMPLIR_PAR_PREFECTURE: " უნდა შეივსოს პრეფექტურის მიერ"
      PREMIERE_DEMANDE: "1-ლი თხოვნა                                       "
      REEXAMEN: "განმეორებითი"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "ინფორმაცია მთხოვნელის სამოქალაქო სტატუსზე "
      NOM: "გვარი"
      PRENOMS: "სახელი"
      NOM_USAGE: "-"
      F: "მდ"
      M: "მმ"
      DATE_NAISSANCE: "დაბადების თარიღი"
      LIEU_NAISSANCE: "დაბადების ადგილი (ქვეყანა და ქალაქი)"
      NATIONALITE: "მოქალაქეობა"
      NOM_PRENOM_PERE: "მამის სახელი და გვარი"
      NOM_PRENOM_MERE: "დედის სახელი და გვარი"
      INFORMATIONS_FAMILLE_DEMANDEUR: "ინფორმაცია მთხოვნელის ოჯახის შესახებ "
      MARIE: "დაოჯახებული"
      CELIBATAIRE: "დასაოჯახებელი"
      VEUF: "ქვრივი"
      DIVORCE: "გაყრილი"
      CONCUBIN: "თანამცხოვრები"
      NOM_CONJOINT: "მეუღლის/პარტნიორის გვარი  (თუ ეს პუნქტი გეხებათ):"
      PRENOM_CONJOINT: "მეუღლის/პარტნიორის სახელი"
      NATIONALITE_CONJOINT: "მეუღლის მოქალაქეობა"
      DATE_LIEU_NAISSANCE_CONJOINT: "მეუღლის დაბადების ადგილი და თარიღი"
      LIEU_RESIDENCE_CONJOINT: " მეუღლის მიმდინარე საცხოვრებელი   ადგილი:"
      NOMBRE_ENFANTS: "შვილების რაოდენობა"
      DONT_ENTRES_EN_FRANCE: "საფრანგეთში მყოფი შვილების     რაოდენობა"
      INDIQUER_TOUS_ENFANTS: "მოგვაწოდეთ ინფორმაცია თქვენს შვილებზე"
      NOM_ENFANT: "გვარი"
      PRENOM_ENFANT: "სახელი"
      NATIONALITE_DATE_LIEU_NAISSANCE: "მოქალაქეობა, დაბადების ადგილი და თარიღი"
      LIEU_RESIDENCE_ACTUELLE: "მიმდინარე საცხოვრებელი მისამართი"
      ADRESSE_COURRIER: "მისამართი, სადაც შესაძლებელია თქვენთვის წერილის გამოგზავნა"
      CHEZ: "ვის  სახელზე"
      NUMERO_VOIE: "N°"
      VOIE: "ქუჩა"
      CODE_POSTAL: "საფოსტო კოდი"
      VILLE: "ქალაქი"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "ინფორმაცია თქვენი საფრანგეთში შემოსვლის და მარშრუტის შესახებ თქვენი ქვეყანის დატოვებიდან  მოყოლებული"
      DATE_DEPART_PAYS_ORIGINE: "თარიღი, როდესაც დატოვეთ თქვენი ქვეყანა და/ან წარმოშობის ქვეყანა (საფრანგეთში წამოსასვლელად)"
      PAYS_TRAVERSES: "რომელი ქვეყანა გადმოლახეთ"
      DATE_ENTREE: "ჩამოსვლის თარიღი"
      DATE_SORTIE: "გამგზავრების თარიღი"
      MOYENS_TRANSPORTS: "გამოყენებული ტრანსპორტის საშუალება"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "როგორ გადმოლახეთ საზღვარი? (ოფიციალურად საზღვრის გადაკვეთის პუნქტის გავლით თუ ფარული გზით)"
      FRANCE: "საფრანგეთი"
      LANGUES: "ენები, რომლებიც გესმით"
      FAIT_LE: "შევსებულია (თარიღი)"
      PREFECTURE_DE: "პრეფექტურა"
      SIGNATURE: "ხელმოწერა "

    LIN:
      NUMERO_ETRANGER: "N° YA BOPAYA "
      RECUEIL_N: "N° YA MUKANDA OYO"
      DATE_DEPOT_DEMANDE: "Mokolo ya bokotisi bosengi "
      A_REMPLIR_PAR_PREFECTURE: "Esika oyo ekokomama na prefecture "
      PREMIERE_DEMANDE: "Bosengi ya yambo"
      REEXAMEN: "Bomenyolami lisusu"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Maye matali bomoyi ya mosengi"
      NOM: "Nkombo ya mboka"
      PRENOMS: "Nkombo mosusu"
      NOM_USAGE: "-"
      F: "Mwasi"
      M: "Mobali"
      DATE_NAISSANCE: "Mokolo ya mbotama"
      LIEU_NAISSANCE: "Esika ya mbotama (mboka mpe engumba)"
      NATIONALITE: "Moyi mboka"
      NOM_PRENOM_PERE: "Nkombo ya mboka na nkombo mosusu ya tata na yo"
      NOM_PRENOM_MERE: "Nkombo ya mboka na nkombo mosusu ya mama na yo"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Maye matali libota ya mosengi"
      MARIE: "Abala"
      CELIBATAIRE: "Monzemba"
      VEUF: "Akufela mwasi/mobali"
      DIVORCE: "Libala esila"
      CONCUBIN: "Makango"
      NOM_CONJOINT: "Nkombo ya molongani, soki azali"
      PRENOM_CONJOINT: "Ba nkombo misusu ya molongani"
      NATIONALITE_CONJOINT: "Moyi mboka ya molongani"
      DATE_LIEU_NAISSANCE_CONJOINT: "Mokolo mpe esika ya mbotama ya molongani"
      LIEU_RESIDENCE_CONJOINT: "Esika molongani na yo avandaka sika oyo"
      NOMBRE_ENFANTS: "Motango ya bana"
      DONT_ENTRES_EN_FRANCE: "Motango ya bana baye bakoti na France"
      INDIQUER_TOUS_ENFANTS: "Tanga bana bayo banso"
      NOM_ENFANT: " Nkombo ya mboka"
      PRENOM_ENFANT: "Nkombo mosusu"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Boyi mboka, mokolo mpe esika ya mbotama"
      LIEU_RESIDENCE_ACTUELLE: "Esika ovandaka sika oyo"
      ADRESSE_COURRIER: "Bisika biye bakoki kotindela yo mikanda"
      CHEZ: "Epayi ya"
      NUMERO_VOIE: "N°"
      VOIE: "Balabala"
      CODE_POSTAL: "Sanduku ya mikanda"
      VILLE: "Egumba"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Maye matali lolenge okotaki na France mpe nzela eye olekelaki banda mboka na yo"
      DATE_DEPART_PAYS_ORIGINE: "Mokolo nini olongwaki o mboka na yo na/to mboka owutelaki"
      PAYS_TRAVERSES: " Ba mboka oyo okatisaki"
      DATE_ENTREE: "Mokolo ya bokoti"
      DATE_SORTIE: "Mokolo ya bobimi"
      MOYENS_TRANSPORTS: "Ekendeli ya mobembo"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: " Ndenge nini okatisaki ndelo? (olekaki na bisika biye bindimami to na kobombama)"
      FRANCE: "France"
      LANGUES: "Nkota eye oyokaka"
      FAIT_LE: "Esalemi na mokolo ya "
      PREFECTURE_DE: "Na prefecture ya"
      SIGNATURE: "MOKOLOTO"

    MON:
      NUMERO_ETRANGER: "ГАДААД ИРГЭНИЙ БҮРТГЭЛИЙН №"
      RECUEIL_N: "ХАВТАСТ ХЭРЭГ№"
      DATE_DEPOT_DEMANDE: "Өргөдөл гаргасан огноо"
      A_REMPLIR_PAR_PREFECTURE: "Тухайн мужийн захиргаа бөглөнө"
      PREMIERE_DEMANDE: "1дэх өргөдөл"
      REEXAMEN: "Дахин хянуулах"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Өргөдөл гаргагчийн иргэний байдлын  тухай мэдээлэл "
      NOM: "Овог "
      PRENOMS: "Нэр"
      NOM_USAGE: "-"
      F: "Эм"
      M: "Эр"
      DATE_NAISSANCE: "Төрсөн огноо"
      LIEU_NAISSANCE: "Төрсөн газар (улс болон хот)"
      NATIONALITE: "Иргэний харьяалал"
      NOM_PRENOM_PERE: "Эцгийн овог ба нэр"
      NOM_PRENOM_MERE: "Эхийн овог ба нэр"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Өргөдөл гаргагчийн гэр бүлийн талаарх мэдээлэл"
      MARIE: "Гэрлэсэн"
      CELIBATAIRE: "Ганц бие"
      VEUF: "Бэлэвсэн"
      DIVORCE: "Салсан"
      CONCUBIN: "Хамтран  амьдрагч"
      NOM_CONJOINT: "Нөхөр/эхнэр/хамтран амьдрагчийн овог нэр, хэрвээ байвал"
      PRENOM_CONJOINT: "Нөхөр/эхнэр/хамтран амьдрагчийн нэр"
      NATIONALITE_CONJOINT: "Нөхөр/эхнэр/хамтран амьдрагч нь аль үндэстэн"
      DATE_LIEU_NAISSANCE_CONJOINT: "Нөхөр/эхнэр/хамтран амьдрагчийн төрсөн огноо ба газар"
      LIEU_RESIDENCE_CONJOINT: "Нөхөр/эхнэр/хамтран амьдрагчийн одоогийн оршин суух газар"
      NOMBRE_ENFANTS: "Хүүхдийн тоо"
      DONT_ENTRES_EN_FRANCE: "Францад байгаа хүүхдийн тоо"
      INDIQUER_TOUS_ENFANTS: "Бүх хүүхдийнхээ тухай мэдээлэл өгнө үү"
      NOM_ENFANT: "Овог нэр"
      PRENOM_ENFANT: "Нэр"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Аль үндэстэн, төрсөн огноо ба газар "
      LIEU_RESIDENCE_ACTUELLE: "Одоогийн оршин суугаа газар"
      ADRESSE_COURRIER: "Танд захиа илгээх хаяг"
      CHEZ: "Хаяган дээрх нэр"
      NUMERO_VOIE: "№"
      VOIE: "Гудамж"
      CODE_POSTAL: "Шуудангийн код"
      VILLE: "Хот "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Та Францад хэрхэн нэвтэрсэн болон төрөлх улсаасаа гарснаас хойшхи аяллын  маршрут"
      DATE_DEPART_PAYS_ORIGINE: "Төрөлх улсаасаа болон/эсвэл Францад ирэхээс өмнөх улсаас гарсан огноо"
      PAYS_TRAVERSES: "Дамжин өнгөрсөн улсууд"
      DATE_ENTREE: "Ирсэн огноо"
      DATE_SORTIE: "Гарсан огноо"
      MOYENS_TRANSPORTS: "Тээврийн  хэрэгсэл"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Хил давсан нөхцлүүд (хилийн албан ёсны зурвасаар эсвэл нууцаар)"
      FRANCE: "Франц"
      LANGUES: "Ойлгодог хэл(нүүд)"
      FAIT_LE: "Үйлдсэн огноо"
      PREFECTURE_DE: "ийн Мужийн захиргаанд"
      SIGNATURE: "ГАРЫН ҮСЭГ"

    PUS:
      NUMERO_ETRANGER: "د بهرنیانو د ثبت شميره"
      RECUEIL_N: "د فایل شميره"
      DATE_DEPOT_DEMANDE: "د درخواست نيټه"
      A_REMPLIR_PAR_PREFECTURE: "دا به ولسوال/قاضی ډکوي"
      PREMIERE_DEMANDE: "لومړې درخواست"
      REEXAMEN: "دوباره کتنه"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "د درخواست ورکونکي د مدني حالت په اړه معلومات  "
      NOM: "کورنې نوم"
      PRENOMS: "[ورکړې شوې] نوم"
      NOM_USAGE: "-"
      F: "نارينه"
      M: "ښځینه"
      DATE_NAISSANCE: "د زيږیدنې نيټه"
      LIEU_NAISSANCE: "د زيږيدنې ځای(هيواد او ښار)"
      NATIONALITE: "تابعيت"
      NOM_PRENOM_PERE: "د پلار کورنې نوم او ورکړې شوې نوم"
      NOM_PRENOM_MERE: "د مور کورنې نوم او ورکړې شوې نوم"
      INFORMATIONS_FAMILLE_DEMANDEUR: "درخواست ورکونکي د کورنۍ په اړه معلومات "
      MARIE: "واده شوې/شوی"
      CELIBATAIRE: "ناواده شوې/شوی"
      VEUF: "کونډه/کونډ"
      DIVORCE: "طلاقه شوې/طلاق شوی"
      CONCUBIN: "ملګرې/ملګری سره ژوند کول"
      NOM_CONJOINT: "د شریکې/شریک کورنې نوم،که وي "
      PRENOM_CONJOINT: "د شریکې/شریک ورکړې شوې نوم"
      NATIONALITE_CONJOINT: " د شریکې/شریک تابعيت"
      DATE_LIEU_NAISSANCE_CONJOINT: " د شریکې/شریک د زيږیدنې ځای او نيټه "
      LIEU_RESIDENCE_CONJOINT: "د شریکې/شریک موجوده د استوګنې ځای            "
      NOMBRE_ENFANTS: "د کوچنيانو شمير"
      DONT_ENTRES_EN_FRANCE: "فرانسه کښې د کوچنيانو شمير"
      INDIQUER_TOUS_ENFANTS: "د خپلو ټولو کوچنيانو پوره تفصيلات ورکړئ"
      NOM_ENFANT: "کورنې نوم"
      PRENOM_ENFANT: "ورکړې شوې نوم"
      NATIONALITE_DATE_LIEU_NAISSANCE: "تابعيت، د زيږیدنې ځای او نيټه"
      LIEU_RESIDENCE_ACTUELLE: "د استوګنې موجوده ځای"
      ADRESSE_COURRIER: "هفه پته چې پرې تاسو ته ليک ترلاسه کيداى شي"
      CHEZ: "په واسطه"
      NUMERO_VOIE: "شمیره"
      VOIE: "کوڅه"
      CODE_POSTAL: "د پوستې کوډ"
      VILLE: "ښار"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "فرانسې ته د داخلیدو په اړه معلومات، او د خپل اصلي هیواد د پریښودلو راهیسې ستا سفرنامه   "
      DATE_DEPART_PAYS_ORIGINE: "د اصلي هیواد د پریښودلو نيټه او/يا هغه هيواد چې تا فرانسې ته راتلو لپاره پريښود "
      PAYS_TRAVERSES: "هغه هيواد چې په سفر ورڅخه تیر شوي یئ"
      DATE_ENTREE: "د داخليدو نيټه   "
      DATE_SORTIE: "د پریښودلو نيټه "
      MOYENS_TRANSPORTS: "د ټرانسپورټ استعمال شوې وسیلې"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "له پولې څرنګه تیر شوې؟(رسمي او که پټه پوله) "
      FRANCE: "فرانسه"
      LANGUES: "ژبه (ې) چې پرې پوهیږئ"
      FAIT_LE: "سرته ورسیده په [نيټه]"
      PREFECTURE_DE: "په ولسوالۍ کې د"
      SIGNATURE: "لاسليک  "

    URD:
      NUMERO_ETRANGER: "غیر ملکی باشندے کا رجسٹریشن نمبر"
      RECUEIL_N: "فائل نمبر"
      DATE_DEPOT_DEMANDE: "درخواست کی تاریخ"
      A_REMPLIR_PAR_PREFECTURE: "سرکاری  دفتر  بھرے گا "
      PREMIERE_DEMANDE: "پہلی درخواست"
      REEXAMEN: "نظر ثانی"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "درخواست دہندہ کی شہری حیثیت کے بارے میں معلومات "
      NOM: "خاندانی نام"
      PRENOMS: "ذاتی نام"
      NOM_USAGE: "-"
      F: "عورت"
      M: "مرد"
      DATE_NAISSANCE: "تاریخ پیدائش"
      LIEU_NAISSANCE: "مقام پیدائش (ملک اور شہر)"
      NATIONALITE: "قومیت"
      NOM_PRENOM_PERE: "والد کا خاندانی اور ذاتی نام"
      NOM_PRENOM_MERE: "والد ہ کا خاندانی اور ذاتی نام"
      INFORMATIONS_FAMILLE_DEMANDEUR: "درخواست دہندہ کے خاندان سے متعلق معلومات"
      MARIE: " شادی شدہ"
      CELIBATAIRE: "غیر شادی شدہ"
      VEUF: "بیوہ"
      DIVORCE: "طلاق یافتہ"
      CONCUBIN: "بغیر شادی کےساتھی"
      NOM_CONJOINT: "شریک حیات کا خاندانی نام، اگر قابل اطلاق ہو"
      PRENOM_CONJOINT: "شریک حیات کا ذاتی  نام"
      NATIONALITE_CONJOINT: "شریک حیات   کی قومیت"
      DATE_LIEU_NAISSANCE_CONJOINT: "شریک حیات   کی تاریخ اور مقام پیدائش"
      LIEU_RESIDENCE_CONJOINT: "شریک حیات   کا حالیہ مقام رہائش"
      NOMBRE_ENFANTS: "بچوں کی تعداد"
      DONT_ENTRES_EN_FRANCE: "فرانس میں بچوں کی تعداد"
      INDIQUER_TOUS_ENFANTS: " اپنے تمام بچوں کی تفصیلی معلومات فراہم کریں"
      NOM_ENFANT: "خاندانی نام"
      PRENOM_ENFANT: "ذاتی نام"
      NATIONALITE_DATE_LIEU_NAISSANCE: "قومیت، تاریخ، اور مقام پیدائش"
      LIEU_RESIDENCE_ACTUELLE: "حالیہ مقام رہائش"
      ADRESSE_COURRIER: "وہ پتہ جہاں آپ کو خطوط بھیجے جا سکتے ہیں"
      CHEZ: "معرفت"
      NUMERO_VOIE: "نمبر "
      VOIE: "گلی"
      CODE_POSTAL: "پوسٹ کوڈ"
      VILLE: "شہر "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "اس بارے میں معلومات کہ آپ فرانس میں کیسے داخل ہوئے اور اپنا آبائی وطن چھوڑنے کے بعد سے آپ کی سفری روئداد"
      DATE_DEPART_PAYS_ORIGINE: "اپنے آبائی وطن اور/ یا فرانس آنے کے لیے ملک سے روانہ ہونے کی تاریخ: "
      PAYS_TRAVERSES: "جس ملک سے سفر کا آغاز کیا"
      DATE_ENTREE: "آمد کی تاریخ"
      DATE_SORTIE: "روانگی کی تاریخ"
      MOYENS_TRANSPORTS: "آمد و رفت کے لیے استعمال کئے جانے والے ذرائع"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "آپ نے ملکی حدود کیسے پار کیں؟ (سرکاری گزر گاہ یا خفیہ گزرگاہ)"
      FRANCE: "فرانس"
      LANGUES: "سمجھ میں آنے والی زبانیں"
      FAIT_LE: "جس تاریخ کو کیا گیا"
      PREFECTURE_DE: "سرکاری دفتر کا نام"
      SIGNATURE: "دستخط"

    POR:
      NUMERO_ETRANGER: "REGISTO DE CIDADÃO ESTRANGEIRO N."
      RECUEIL_N: "PROCESSO N. "
      DATE_DEPOT_DEMANDE: "Data de depósito do pedido:"
      A_REMPLIR_PAR_PREFECTURE: "A preencher pela prefeitura"
      PREMIERE_DEMANDE: "1.º pedido"
      REEXAMEN: "Reapreciação"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Indicações relativas ao estado civil do requerente"
      NOM: "Apelido"
      PRENOMS: "Nome(s)"
      NOM_USAGE: "-"
      F: "-"
      M: "-"
      DATE_NAISSANCE: "Data de nascimento"
      LIEU_NAISSANCE: "Local de nascimento (país e cidade)"
      NATIONALITE: "Nacionalidade"
      NOM_PRENOM_PERE: "Apelido e nome do pai"
      NOM_PRENOM_MERE: "Apelido e nome da mãe"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Indicações relativas à família do requerente"
      MARIE: "Casado(a)"
      CELIBATAIRE: "Solteiro(a)"
      VEUF: "Viúvo(a)"
      DIVORCE: "Divorciado(a)"
      CONCUBIN: "Concubino(a)"
      NOM_CONJOINT: "Apelido do cônjuge, se aplicável"
      PRENOM_CONJOINT: "Nome do cônjuge"
      NATIONALITE_CONJOINT: "Nacionalidade do cônjuge"
      DATE_LIEU_NAISSANCE_CONJOINT: "Data e local de nascimento do cônjuge"
      LIEU_RESIDENCE_CONJOINT: "Local de residência atual do cônjuge"
      NOMBRE_ENFANTS: "Número de filhos"
      DONT_ENTRES_EN_FRANCE: "que entraram em França"
      INDIQUER_TOUS_ENFANTS: "Indicar o número total de filhos"
      NOM_ENFANT: "Apelido"
      PRENOM_ENFANT: "Nome"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Nacionalidade, data e local de nascimento"
      LIEU_RESIDENCE_ACTUELLE: "Local de residência atual"
      ADRESSE_COURRIER: "Indicação do endereço para onde se pode enviar a correspondência"
      CHEZ: "Em casa de"
      NUMERO_VOIE: "N"
      VOIE: "Rua"
      CODE_POSTAL: "Código postal"
      VILLE: "Cidade"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Indicações acerca das condições de entrada em França e dos itinerários de viagem a partir do país de origem"
      DATE_DEPART_PAYS_ORIGINE: "Data de partida do país de origem e/ou de proveniência "
      PAYS_TRAVERSES: "Países atravessados"
      DATE_ENTREE: "Data de entrada"
      DATE_SORTIE: "Data de saída"
      MOYENS_TRANSPORTS: "Meios de transporte"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Condições de passagem das fronteiras (ponto de passagem autorizado ou evitando os pontos de controlo)"
      FRANCE: "França"
      LANGUES: "Idioma(s) entendido(s)"
      FAIT_LE: "Feito em"
      PREFECTURE_DE: "Na prefeitura de"
      SIGNATURE: "ASSINATURA"

    RUM:
      NUMERO_ETRANGER: "NR. STRĂIN"
      RECUEIL_N: "NR. DOSAR"
      DATE_DEPOT_DEMANDE: "Data depunerii cererii"
      A_REMPLIR_PAR_PREFECTURE: "A se completa de către prefectură"
      PREMIERE_DEMANDE: "Prima cerere"
      REEXAMEN: "Reexaminare"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Informaţii privind starea civilă a solicitantului"
      NOM: "Numele de familie"
      PRENOMS: "Prenumele"
      NOM_USAGE: "-"
      F: "-"
      M: "-"
      DATE_NAISSANCE: "Data naşterii"
      LIEU_NAISSANCE: "Locul naşterii (ţara şi oraşul)"
      NATIONALITE: "Naţionalitate"
      NOM_PRENOM_PERE: "Numele şi prenumele tatălui"
      NOM_PRENOM_MERE: "Numele şi prenumele mamei"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Informaţii privind familia solicitantului"
      MARIE: "Căsătorit(ă)"
      CELIBATAIRE: "Necăsătorit(ă)"
      VEUF: "Văduv(ă)"
      DIVORCE: "Divorţat(ă)"
      CONCUBIN: "În concubinaj"
      NOM_CONJOINT: "Numele soţului/soţiei, dacă este cazul"
      PRENOM_CONJOINT: "Prenumele soţului/soţiei"
      NATIONALITE_CONJOINT: "Naţionalitatea soţului/soţiei"
      DATE_LIEU_NAISSANCE_CONJOINT: "Data şi locul naşterii soţului/soţiei"
      LIEU_RESIDENCE_CONJOINT: "Locul de reşedinţă actuală al soţului/soţiei"
      NOMBRE_ENFANTS: "Numărul de copii"
      DONT_ENTRES_EN_FRANCE: "din care în Franţa"
      INDIQUER_TOUS_ENFANTS: "Indicaţi fiecare copil"
      NOM_ENFANT: "Numele de familie"
      PRENOM_ENFANT: "Prenumele"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Naţionalitatea, data şi locul naşterii"
      LIEU_RESIDENCE_ACTUELLE: "Locul de reşedinţă actuală"
      ADRESSE_COURRIER: "Adresa unde vă putem trimite corespondenţa"
      CHEZ: "La (destinatar intermediar)"
      NUMERO_VOIE: "Nr"
      VOIE: "Strada"
      CODE_POSTAL: "Cod poştal"
      VILLE: "Oraş"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Informaţii despre condiţiile în care aţi intrat în Franţa şi traseul parcurs de la plecarea din ţara de origine"
      DATE_DEPART_PAYS_ORIGINE: "Data plecării din ţara de origine şi/sau din ţara de unde veniţi în Franţa"
      PAYS_TRAVERSES: "Ţări tranzitate"
      DATE_ENTREE: "Data intrării"
      DATE_SORTIE: "Data ieşirii"
      MOYENS_TRANSPORTS: "Mijloace de transport "
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Condiţii de trecere a frontierelor (punct de trecere autorizat sau evitând punctele de control)"
      FRANCE: "Franţa"
      LANGUES: "Limbile pe care le înţelegeţi"
      FAIT_LE: "Făcut pe"
      PREFECTURE_DE: "La prefectura din"
      SIGNATURE: "SEMNĂTURA"

    RUS:
      NUMERO_ETRANGER: "РЕГИСТРАЦИОННЫЙ № ИНОСТРАНЦА"
      RECUEIL_N: "ФАЙЛ №"
      DATE_DEPOT_DEMANDE: "Дата заявки"
      A_REMPLIR_PAR_PREFECTURE: "Заполняется префектурой"
      PREMIERE_DEMANDE: "1-я заявка"
      REEXAMEN: "Повторное рассмотрение"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Информация о гражданском состоянии заявителя "
      NOM: "Фамилия"
      PRENOMS: "Имя"
      NOM_USAGE: "-"
      F: "Ж"
      M: "M"
      DATE_NAISSANCE: "Дата рождения"
      LIEU_NAISSANCE: "Место рождения (страна и город)"
      NATIONALITE: "Национальность"
      NOM_PRENOM_PERE: "Имя и фамилия отца"
      NOM_PRENOM_MERE: "Имя и фамилия матери"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Информация о семье заявителя "
      MARIE: "Состою в браке"
      CELIBATAIRE: "Холост/Не замужем"
      VEUF: "Вдовец/Вдова"
      DIVORCE: "В разводе"
      CONCUBIN: "Сожительство"
      NOM_CONJOINT: "Фамилия партнера (если применимо)"
      PRENOM_CONJOINT: "Имя партнера"
      NATIONALITE_CONJOINT: "Национальность партнера"
      DATE_LIEU_NAISSANCE_CONJOINT: "Дата и место рождения партнера"
      LIEU_RESIDENCE_CONJOINT: "Текущее место жительства партнера"
      NOMBRE_ENFANTS: "Количество детей"
      DONT_ENTRES_EN_FRANCE: "Количество детей во Франции"
      INDIQUER_TOUS_ENFANTS: "Приведите информацию обо всех детях"
      NOM_ENFANT: "Фамилия"
      PRENOM_ENFANT: "Имя"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Национальность, дата и место рождения"
      LIEU_RESIDENCE_ACTUELLE: "Текущее место жительства"
      ADRESSE_COURRIER: "Адрес для корреспонденции"
      CHEZ: "Кому"
      NUMERO_VOIE: "№ "
      VOIE: "Улица"
      CODE_POSTAL: "Почтовый индекс"
      VILLE: "Город"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Информация о вашем въезде во Францию и маршруте после выезда и страны отправления"
      DATE_DEPART_PAYS_ORIGINE: "Дата выезда из страны проживания и/или страны, из которой вы отправились во Францию"
      PAYS_TRAVERSES: "Страна проезда"
      DATE_ENTREE: "Дата прибытия"
      DATE_SORTIE: "Дата отъезда"
      MOYENS_TRANSPORTS: "Используемые транспортные средства"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Как вы пересекли границу? (официальный пограничный переход или нелегально)"
      FRANCE: "Франция"
      LANGUES: "Используемые языки"
      FAIT_LE: "Составлено"
      PREFECTURE_DE: "В префектуре"
      SIGNATURE: "ПОДПИСЬ"

    SRP:
      NUMERO_ETRANGER: "BROJ STRANCA"
      RECUEIL_N: "BROJ PREDMETA"
      DATE_DEPOT_DEMANDE: "Datum podnošenja zahteva"
      A_REMPLIR_PAR_PREFECTURE: "Deo koji popunjava uprava policije"
      PREMIERE_DEMANDE: "Prvi zahtev"
      REEXAMEN: "Ponovljen zahtev"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Lični podaci o tražiocu"
      NOM: "Prezime"
      PRENOMS: "Ime (imena)"
      NOM_USAGE: "-"
      F: "~Z"
      M: "M"
      DATE_NAISSANCE: "Datum rođenja"
      LIEU_NAISSANCE: "Mesto rođenja (zemlja i grad)"
      NATIONALITE: "Državljanstvo"
      NOM_PRENOM_PERE: "Prezime i ime oca"
      NOM_PRENOM_MERE: "Prezime i ime majke"
      INFORMATIONS_FAMILLE_DEMANDEUR: " Informacije vezane za porodicu tražioca"
      MARIE: "U braku"
      CELIBATAIRE: "Neo~zenjen/neudata"
      VEUF: "Udovac(ica)"
      DIVORCE: "Razveden(a)"
      CONCUBIN: "Nevenčana zajednica"
      NOM_CONJOINT: "Prezime supružnika, ako je taj slučaj u pitanju"
      PRENOM_CONJOINT: "Ime supružnika"
      NATIONALITE_CONJOINT: " Državljanstvo supružnika"
      DATE_LIEU_NAISSANCE_CONJOINT: " Datum i mesto rođenja supružnika"
      LIEU_RESIDENCE_CONJOINT: "Mesto u kome trenutno boravi supružnik"
      NOMBRE_ENFANTS: "Broj dece"
      DONT_ENTRES_EN_FRANCE: "Broj dece koja su ušla u Francusku"
      INDIQUER_TOUS_ENFANTS: "Podaci o svakom detetu"
      NOM_ENFANT: "Prezime"
      PRENOM_ENFANT: "Ime"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Dr~zavljanstvo, datum i mesto  rođenja"
      LIEU_RESIDENCE_ACTUELLE: "Mesto u kome trenutno boravi"
      ADRESSE_COURRIER: "Adresa na koju vam možemo slati poštu"
      CHEZ: "Kod gospodina/gospođe"
      NUMERO_VOIE: "Br"
      VOIE: "Ulica"
      CODE_POSTAL: "Poštanski broj"
      VILLE: "Grad "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Informacije o uslovima ulaska u Francusku i o maršuti putovanja od zemlje porekla"
      DATE_DEPART_PAYS_ORIGINE: "Datum polaska iz zemlje porekla i/ili zemlje iz koje dolazite "
      PAYS_TRAVERSES: "Zemlje kroz koje ste prošli"
      DATE_ENTREE: "Datum ulaska"
      DATE_SORTIE: "Datum izlaska"
      MOYENS_TRANSPORTS: "Prevozna sredstva"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Kako ste prešli granicu? (preko službenog graničnog prelaza ili ilegalno)"
      FRANCE: "Francuska"
      LANGUES: "Jezik (jezici) koje razumete"
      FAIT_LE: "Datum"
      PREFECTURE_DE: "Uprava policije u"
      SIGNATURE: "POTPIS"

    SWA:
      NUMERO_ETRANGER: "NAMBA WA MGENI"
      RECUEIL_N: "NAMBA YA FAILI"
      DATE_DEPOT_DEMANDE: "Tarehe ya maombi"
      A_REMPLIR_PAR_PREFECTURE: "Jaza Fomu ya Maombi iliyoelezwa katika Wilaya"
      PREMIERE_DEMANDE: "Ombi la kwanza"
      REEXAMEN: "Uzingatiaji upya"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "6  Maelezo kuhusu hali ya kiraia ya mwombaji"
      NOM: "Jina la Ukoo"
      PRENOMS: "Jina la Kwanza "
      NOM_USAGE: "-"
      F: "KIKE"
      M: "KIUME"
      DATE_NAISSANCE: "Tarehe ya kuzaliwa"
      LIEU_NAISSANCE: "Mahali pa kuzaliwa (nchi na jiji)"
      NATIONALITE: "Utaifa"
      NOM_PRENOM_PERE: "Jina Kamili la Baba"
      NOM_PRENOM_MERE: "Jina Kamili la Mama"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Maelezo kuhusu jamaa wa mwombaji"
      MARIE: "Nina Ndoa"
      CELIBATAIRE: "Sina Ndoa"
      VEUF: "Mfiwa"
      DIVORCE: "Mtalaka"
      CONCUBIN: "Mwenzi"
      NOM_CONJOINT: "Jina la Ukoo ya mwanamke au mwanamume , kama lipo"
      PRENOM_CONJOINT: " Jina Kwanza  la mwanamke au mwanamume "
      NATIONALITE_CONJOINT: "Utaifa wa mwanamke au mwanamume "
      DATE_LIEU_NAISSANCE_CONJOINT: "Tarehe na Mahali ya mwanamke au mwanamume "
      LIEU_RESIDENCE_CONJOINT: "Mahali la makazi ya sasa ya mwanamke au mwanamume"
      NOMBRE_ENFANTS: "Idadi ya watoto"
      DONT_ENTRES_EN_FRANCE: "Idadi ya watoto Ufaransa"
      INDIQUER_TOUS_ENFANTS: "Toa maelezo ya watoto wako wote"
      NOM_ENFANT: "Jina la Ukoo"
      PRENOM_ENFANT: "Jina la Kwanza "
      NATIONALITE_DATE_LIEU_NAISSANCE: "Utaifa, tarehe na Mahali la kuzaliwa"
      LIEU_RESIDENCE_ACTUELLE: "Mahali la sasa la makazi"
      ADRESSE_COURRIER: "Anwani  ya posta"
      CHEZ: "Kwa uangalizi wa"
      NUMERO_VOIE: "Namba "
      VOIE: "Mtaa "
      CODE_POSTAL: "Msimbo posta"
      VILLE: "Jiji "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Habari juu ya hali ya kuingia ndani ya Ufaransa na kusafiri njia kutoka nchi ya asili "
      DATE_DEPART_PAYS_ORIGINE: "Tarehe ya kuondoka katika nchi yako asili na/au nchi uliyotoka ili kukuja Ufaransa"
      PAYS_TRAVERSES: "Nchi uliyopitia ukisafiri"
      DATE_ENTREE: "Tarehe ya kuingia"
      DATE_SORTIE: "Tarehe ye kuondoka"
      MOYENS_TRANSPORTS: "Mbinu za usafiri zilizotumiwa"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Masharti kwa ajili ya kuvuka mipaka (mahali la kuvuka kirasmi au kuvuka kisiri)"
      FRANCE: "Ufaransa"
      LANGUES: "Lugha unazoelewa"
      FAIT_LE: "Ilitayarishwa mnamo"
      PREFECTURE_DE: "Katika wilaya ya"
      SIGNATURE: "SAHIHI"

    TAM:
      NUMERO_ETRANGER: "அயல்நாட்டவர் பதிவு எண்"
      RECUEIL_N: "கோப்பு எண்"
      DATE_DEPOT_DEMANDE: "விண்ணப்பிக்கும் தேதி"
      A_REMPLIR_PAR_PREFECTURE: "தலைமைப் பதவியில் இருப்பவரால் நிரப்பப்பட வேண்டும்"
      PREMIERE_DEMANDE: "1வது விண்ணப்பம்"
      REEXAMEN: "மறு பரிசீலனை"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "விண்ணப்பதாரரின் குடியுரிமை நிலை பற்றிய தகவல்"
      NOM: "குடும்பப் பெயர் "
      PRENOMS: "முதல் பெயர் "
      NOM_USAGE: "-"
      F: "-"
      M: "-"
      DATE_NAISSANCE: "பிறந்த தேதி "
      LIEU_NAISSANCE: "பிறந்த இடம் (நாடு மற்றும் நகரம்)"
      NATIONALITE: "நாட்டுரிமை"
      NOM_PRENOM_PERE: "தந்தையின் குடும்பப் பெயர் மற்றும் முதல் பெயர் "
      NOM_PRENOM_MERE: "தாயாரின் குடும்பப் பெயர் மற்றும் முதல் பெயர்  "
      INFORMATIONS_FAMILLE_DEMANDEUR: "விண்ணப்பதாரரின் குடும்பத்தினைப் பற்றிய தகவல்"
      MARIE: "திருமணமானவர்"
      CELIBATAIRE: "திருமணமாகாதவர்"
      VEUF: "வாழ்க்கைத் துணையை இழந்தவர்"
      DIVORCE: "விவாகரத்து பெற்றவர்"
      CONCUBIN: "கூடி வாழ்பவர்"
      NOM_CONJOINT: "வாழ்க்கைத் துணையின் குடும்பப் பெயர், பொருந்தினால்:"
      PRENOM_CONJOINT: "வாழ்க்கைத் துணையின் முதல் பெயர்"
      NATIONALITE_CONJOINT: "வாழ்க்கைத் துணையின் நாட்டுரிமை"
      DATE_LIEU_NAISSANCE_CONJOINT: "வாழ்க்கைத் துணையின் பிறந்த தேதி மற்றும் பிறந்த இடம்"
      LIEU_RESIDENCE_CONJOINT: "வாழ்க்கைத் துணையின் தற்போதைய வசிப்பிடம்"
      NOMBRE_ENFANTS: "குழந்தைகளின் எண்ணிக்கை:"
      DONT_ENTRES_EN_FRANCE: "ஃபிரான்ஸில் உள்ள குழந்தைகளின் எண்ணிக்கை"
      INDIQUER_TOUS_ENFANTS: "உங்கள் அனைத்துக் குழந்தைகளின் விவரங்களையும் வழங்கவும்"
      NOM_ENFANT: "குடும்பப் பெயர்"
      PRENOM_ENFANT: "முதல் பெயர்"
      NATIONALITE_DATE_LIEU_NAISSANCE: "நாட்டுரிமை, பிறந்த தேதி மற்றும் பிறந்த இடம்"
      LIEU_RESIDENCE_ACTUELLE: "தற்போதைய வசிப்பிடம்"
      ADRESSE_COURRIER: "உங்களுக்குக் கடிதங்கள் அனுப்பப்படக் கூடிய முகவரி"
      CHEZ: "காப்பாளர் "
      NUMERO_VOIE: "எண் "
      VOIE: "தெரு "
      CODE_POSTAL: "அஞ்சல் குறியீடு: "
      VILLE: "நகரம் "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "நீங்கள் எவ்வாறு ஃபிரான்ஸிற்குள் நுழைந்தீர்கள் என்பதன் மீதான தகவல்கள் மற்றும் நீங்கள் உங்கள் பூர்வீக நாட்டிலிருந்து கிளம்பியதிலிருந்து உங்களின் பயணத் திட்டம் "
      DATE_DEPART_PAYS_ORIGINE: "உங்கள் பூர்வீக நாட்டிலிருந்து மற்றும் / அல்லது நீங்கள் கிளம்பிய நாட்டிலிருந்து ஃபிரான்ஸிற்கு நீங்கள் புறப்பட்ட தேதி"
      PAYS_TRAVERSES: "எந்த நாட்டின் வழியாகப் பயணித்தீர்கள்"
      DATE_ENTREE: "வந்து சேர்ந்த தேதி"
      DATE_SORTIE: "புறப்பட்ட தேதி"
      MOYENS_TRANSPORTS: "பயன்படுத்திய போக்குவரத்து வழிவகைகள்"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "நீங்கள் எவ்வாறு எல்லையைக் கடந்தீர்கள் (அதிகாரப் பூர்வமாகக் கடக்கும் புள்ளி அல்லது திருட்டுத்தனமாகக் கடந்து வரும் புள்ளி)"
      FRANCE: "ஃபிரான்ஸ்"
      LANGUES: "புரிந்துகொள்ளும் மொழி(கள்)"
      FAIT_LE: "செய்யப்பட்ட நாள்"
      PREFECTURE_DE: "தலைமைப் பதவியில் இருப்பவருக்கு"
      SIGNATURE: "கையொப்பம்"

    CHE:
      NUMERO_ETRANGER: "КХЕЧУ ПАЧХЬАКЧАР ВЕАНЧУ СТЕГА  N°"
      RECUEIL_N: "ДОСЬЕ N°"
      DATE_DEPOT_DEMANDE: "Дечар дина терахь"
      A_REMPLIR_PAR_PREFECTURE: "Префектурас язъдан деза"
      PREMIERE_DEMANDE: "1 дехар"
      REEXAMEN: "юхталлар дехар"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Дехархочунна гражданский состоянех йолу информаци "
      NOM: "Фамили"
      PRENOMS: "Ц1е"
      NOM_USAGE: "-"
      F: "Сте"
      M: "Б"
      DATE_NAISSANCE: "Вина-йина де"
      LIEU_NAISSANCE: "Вина-йина меттиг  (пачхьалкх, г1ала)"
      NATIONALITE: "Гражданство"
      NOM_PRENOM_PERE: "Де ц1е"
      NOM_PRENOM_MERE: "Нена ц1е"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Дехархочуьнна доьзалех йолу информаци"
      MARIE: "Зуд ялин-марехь"
      CELIBATAIRE: "Ялоз - яхаз"
      VEUF: "Зуд елла 1аш-йиссан 1аш"
      DIVORCE: "Д1аскьестан"
      CONCUBIN: "Мах ца беш цхьан 1аш"
      NOM_CONJOINT: "X1усам де–нена фамили, нагахь ялахь"
      PRENOM_CONJOINT: "X1усам де–нена ц1е "
      NATIONALITE_CONJOINT: "X1усам де–нена гражданство "
      DATE_LIEU_NAISSANCE_CONJOINT: "Х1усам да-нана йина де а, меттиг а "
      LIEU_RESIDENCE_CONJOINT: "1aш йолу-волу меттиг "
      NOMBRE_ENFANTS: "Масса ву доьзалхо"
      DONT_ENTRES_EN_FRANCE: "масса доьзалхо ву Францехь"
      INDIQUER_TOUS_ENFANTS: "Массо берашан данныш яз де "
      NOM_ENFANT: "Фамили"
      PRENOM_ENFANT: "Ц1е"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Гражданство а, вина меттиг а"
      LIEU_RESIDENCE_ACTUELLE: "1яш волу меттиг"
      ADRESSE_COURRIER: "Шуна кехат д1а даийта бакьо йолу адрес"
      CHEZ: "Хусаман де ц1е"
      NUMERO_VOIE: "N° "
      VOIE: "Урам ц1е "
      CODE_POSTAL: "Почтан индекс"
      VILLE: " Г1ала "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Информация о том, как вы въехали во Францию и о вашем маршруте с момента выезда из вашей страны."
      DATE_DEPART_PAYS_ORIGINE: "Дата выезда из вашей страны и/или страны из, которой вы выехали и въехали во Францию "
      PAYS_TRAVERSES: "Страна, которую пересекли"
      DATE_ENTREE: " Дата заезда"
      DATE_SORTIE: "Дата выезда"
      MOYENS_TRANSPORTS: "На каком транспорте"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Как вы пересекли границу?(точка официального пересечения или нелегальное пересечение  )"
      FRANCE: "Франц"
      LANGUES: "Язык(и), на котором понимает"
      FAIT_LE: "Дата составления"
      PREFECTURE_DE: "Префектура"
      SIGNATURE: "КУЬГ ТА1О ДЕЗА МЕТТИГ "

    TIR:
      NUMERO_ETRANGER: "ቊ. ምዝገባ ወጻእተኛ፥:"
      RECUEIL_N: "ቊ. ፋይል፥"
      DATE_DEPOT_DEMANDE: "መመልከቲ ዚቐረበሉ ዕለት፥"
      A_REMPLIR_PAR_PREFECTURE: "ብቤት ጽሕፈት ኣውርጃ ይምላእ"
      PREMIERE_DEMANDE: "1ይ መመልከቲ"
      REEXAMEN: "ዳግማይ-ምርኣይ መመልከቲ"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "ብዛዕባ ስቪላዊ ኲነታት ኣመልካቲ ዚምልከት ሓበሬታ"
      NOM: "ስም ኣቦ፥"
      PRENOMS: "ስም፥"
      NOM_USAGE: "-"
      F: "ኣን"
      M: "ተባ"
      DATE_NAISSANCE: "ዕለተ-ልደት፥ "
      LIEU_NAISSANCE: "ቦታ ልደት (ሃገርን ከተማን)"
      NATIONALITE: "ዜግነት፥"
      NOM_PRENOM_PERE: "ስም ኣቦን ኣቦ-ሓጐን፥"
      NOM_PRENOM_MERE: "ስም ኣደን ኣቦ-ሓጐን፥"
      INFORMATIONS_FAMILLE_DEMANDEUR: "ብዛዕባ ስድራቤት ኣመልካቲ ዚምልከት ሓበሬታ"
      MARIE: "ምርዕው/ቲ"
      CELIBATAIRE: "ዘይምርዕው/ቲ"
      VEUF: "መበለት/ማእምን"
      DIVORCE: "ፍቱሕ/ፍትሕቲ"
      CONCUBIN: "ምስ ኣንጻር ጾታ ብሓደ ዚቕመጥ ሰብ"
      NOM_CONJOINT: "ስም ኣቦ መጻምዲ/ቲ፡ ዝምልከት እንተኾይኑ፥"
      PRENOM_CONJOINT: "ስም መጻምዲ/ቲ፥"
      NATIONALITE_CONJOINT: "ዜግነት መጻምዲ/ቲ፥"
      DATE_LIEU_NAISSANCE_CONJOINT: "ዕለትን ቦታን ልደት መጻምዲ/ቲ፥"
      LIEU_RESIDENCE_CONJOINT: "እዋናዊ መንበሪ ቦታ መጻምዲ/ቲ፥"
      NOMBRE_ENFANTS: "ብዝሒ ቆልዑ፥"
      DONT_ENTRES_EN_FRANCE: "ብዝሒ’ቶም ኣብ ፈረንሳ ዘለዉ ቆልዑ፥"
      INDIQUER_TOUS_ENFANTS: "ዝርዝር ሓበሬታ ኲሎም ደቅኹም ሃቡ"
      NOM_ENFANT: "ስም ኣቦ"
      PRENOM_ENFANT: "ስም"
      NATIONALITE_DATE_LIEU_NAISSANCE: "ዜግነት፡ ዕለትን ቦታን ልደት"
      LIEU_RESIDENCE_ACTUELLE: "እዋናዊ መንበሪ ቦታ፥"
      ADRESSE_COURRIER: "ደብዳቤታት ናባኹም ዝስደደሉ ኣድራሻ"
      CHEZ: "ኣብ ክንዲ፥"
      NUMERO_VOIE: "ቊ "
      VOIE: "ጐደና፥"
      CODE_POSTAL: "ፖስት ኮድ፥ "
      VILLE: "ከተማ፥"
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "ናብ ፈረንሳ ብኸመይ ከምዝኣተኹምን ካብ መበቆል ሃገርኩም ክሳዕ ኣብዚ እትበጽሑ ብዛዕባ ዝነበረ ኲነታት ጉዕዞኹም ዚምልከት ሓበሬታ"
      DATE_DEPART_PAYS_ORIGINE: "ካብ መበቆል ሃገርኩም ከምኡውን/ወይ ናብ ፈረንሳ ካብ ዝመጻእክሙሉ ሃገር ዝተበገስክሙሉ ዕለት፥ "
      PAYS_TRAVERSES: "ናብዛ ሃገር ንኽትመጹ ዝሓለፍክሙለን ሃገራት"
      DATE_ENTREE: "ዝበጻሕክሙሉ ዕለት"
      DATE_SORTIE: "ዝተበገስክሙሉ ዕለት"
      MOYENS_TRANSPORTS: "ዝተጠቐምክሙሉ ኣገባብ መጓዓዝያ"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "ንዶብ ብኸመይ ሰጊርኩም? (ወግዓዊ መሳገሪ ዶብ ወይ ምስጢራዊ መሳገሪ ዶብ)"
      FRANCE: "ፈረንሳ"
      LANGUES: "እትርድእዎ ቛንቋ(ታት)፥"
      FAIT_LE: "ዕለት፥"
      PREFECTURE_DE: "ዝተኻየደሉ ቤት ጽሕፈት ኣውራጃ፥"
      SIGNATURE: "ክታም፥"

    TUR:
      NUMERO_ETRANGER: "YABANCI KAYIT NO"
      RECUEIL_N: "DOSYA NO"
      DATE_DEPOT_DEMANDE: "Başvuru tarihi"
      A_REMPLIR_PAR_PREFECTURE: "Valilik tarafından doldurulacaktır"
      PREMIERE_DEMANDE: "  İlk başvuru"
      REEXAMEN: "Yeniden inceleme talebi"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Başvuru sahibininnüfus bilgileri"
      NOM: "Soyadı"
      PRENOMS: "Adı"
      NOM_USAGE: "-"
      F: "K"
      M: "E"
      DATE_NAISSANCE: "Doğum tarihi"
      LIEU_NAISSANCE: "Doğum yeri (ülke ve şehir)"
      NATIONALITE: "Uyruğu"
      NOM_PRENOM_PERE: "Baba soyadı ve adı"
      NOM_PRENOM_MERE: "Anne soyadı ve adı"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Başvuru sahibinin ailesine yönelikbilgiler"
      MARIE: "Evli"
      CELIBATAIRE: "Bekâr"
      VEUF: "Dul"
      DIVORCE: "Boşanmış"
      CONCUBIN: "Resmi nikâhsız eş"
      NOM_CONJOINT: "Varsa, eşinin soyadı"
      PRENOM_CONJOINT: "Eşinin adı"
      NATIONALITE_CONJOINT: "Eşin Milliyet"
      DATE_LIEU_NAISSANCE_CONJOINT: " Eşinin doğum yeri ve tarihi "
      LIEU_RESIDENCE_CONJOINT: "Eşinin mevcut ikamet yeri"
      NOMBRE_ENFANTS: "Çocuk sayısı"
      DONT_ENTRES_EN_FRANCE: "Fransa'ya giriş yapmış olan çocuk sayısı"
      INDIQUER_TOUS_ENFANTS: "Çocuklar ile ilgili tüm ayrıntıları belirtin"
      NOM_ENFANT: "Soyadı"
      PRENOM_ENFANT: "Adı"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Uyruğu, doğum tarihi ve yeri"
      LIEU_RESIDENCE_ACTUELLE: "Mevcut ikamet yeri"
      ADRESSE_COURRIER: "Size posta yolu ile ulaşılabilecek adres"
      CHEZ: "Sizi barındıran kişi"
      NUMERO_VOIE: "No"
      VOIE: "Sokak "
      CODE_POSTAL: "Posta kodu"
      VILLE: "Şehir "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Fransa'ya giriş koşullarınız ve geldiğiniz ülkeden Fransa'ya seyahat ederken kullandığınız güzergâhlar ile ilgili bilgiler"
      DATE_DEPART_PAYS_ORIGINE: "Menşe ülke ve/veya geldiğiniz ülkeden ayrıldığınız tarih"
      PAYS_TRAVERSES: "Geçtiğiniz ülkeler"
      DATE_ENTREE: "Giriş yaptığınız tarih"
      DATE_SORTIE: "Çıkış yaptığınız tarih"
      MOYENS_TRANSPORTS: "Kullandığınız taşıma araçları"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Sınırı nasıl aştınız? (resmi geçiş noktasından geçerek veya kontrol noktalarından geçmeden)"
      FRANCE: "Fransa"
      LANGUES: "Anladığı dil(ler)"
      FAIT_LE: "Düzenlendiği yer"
      PREFECTURE_DE: "Valiliği"
      SIGNATURE: "İMZA"

    VIE:
      NUMERO_ETRANGER: "SỐ TỊ NẠN"
      RECUEIL_N: "SỐ HỒ Sơ"
      DATE_DEPOT_DEMANDE: "Ngày nộp hồ sơ"
      A_REMPLIR_PAR_PREFECTURE: "Dành cho Văn phòng Tỉnh"
      PREMIERE_DEMANDE: "Lần đầu"
      REEXAMEN: "Xét lại"
      INDICATIONS_ETAT_CIVIL_DEMANDEUR: "Tình trạng dân sự của người nộp đơn"
      NOM: "Họ"
      PRENOMS: "Tên"
      NOM_USAGE: "Nữ"
      F: "Nữ"
      M: "Nam"
      DATE_NAISSANCE: "Ngày sinh"
      LIEU_NAISSANCE: "Nơi sinh (tên nước và thành phố)"
      NATIONALITE: "Quốc tịch"
      NOM_PRENOM_PERE: "Họ và tên cha"
      NOM_PRENOM_MERE: "Họ và tên mẹ"
      INFORMATIONS_FAMILLE_DEMANDEUR: "Thông tin về gia đình người nộpđơn"
      MARIE: "Đã kết hôn"
      CELIBATAIRE: "Độc thân"
      VEUF: "Góa chồng (vợ)"
      DIVORCE: "Ly dị"
      CONCUBIN: "Sống chung"
      NOM_CONJOINT: "Họ của vợ/chồng nếu có"
      PRENOM_CONJOINT: "Tên của vợ/chồng"
      NATIONALITE_CONJOINT: "Quốc tịch của vợ/chồng"
      DATE_LIEU_NAISSANCE_CONJOINT: "Ngày sinh và nơi sinh của vợ/chồng"
      LIEU_RESIDENCE_CONJOINT: "Địa chỉ cư trú hiện tại của vợ/chồng"
      NOMBRE_ENFANTS: "Số con"
      DONT_ENTRES_EN_FRANCE: "Số con ở Pháp"
      INDIQUER_TOUS_ENFANTS: "Khai rõ tất cả các con"
      NOM_ENFANT: "Họ"
      PRENOM_ENFANT: "Tên"
      NATIONALITE_DATE_LIEU_NAISSANCE: "Quốc tich, ngày sinh, nơi sinh"
      LIEU_RESIDENCE_ACTUELLE: "Chỗ ở hiện tại"
      ADRESSE_COURRIER: "Địa chỉ nhận thư liên hệ"
      CHEZ: "Tên"
      NUMERO_VOIE: "Số"
      VOIE: "Phố"
      CODE_POSTAL: "Mã bưu điện"
      VILLE: "Thành phố "
      INFORMATIONS_CONDITIONS_ENTREE_FRANCE: "Cách thức nhập cảnh vào Pháp và lộ trình đến Pháp từ nước xuất xứ"
      DATE_DEPART_PAYS_ORIGINE: "Ngày xuất phát từ nước xuất xứ và/hoặc các nước quá cảnh trước khi tới Pháp"
      PAYS_TRAVERSES: "Nước đã đi qua"
      DATE_ENTREE: "Ngày nhập  cảnh"
      DATE_SORTIE: "Ngày xuất cảnh"
      MOYENS_TRANSPORTS: "Phương tiện đi lại"
      CONDITIONS_FRANCHISSEMENT_FRONTIERES: "Phương thức qua biên giới (đi qua hợp pháp hay trốn tránh kiểm tra)"
      FRANCE: "Pháp"
      LANGUES: "Ngôn ngữ sử dụng được "
      FAIT_LE: "Lập ngày"
      PREFECTURE_DE: "Tại"
      SIGNATURE: "CHỮ KÝ"

      # PROFIL_DEMANDE: "Demand profile"
      # STATUT_RECUEIL: "Status of the collection"
      # TYPE_USAGER:
      #   usager1: "user 1"
      #   usager2: "user 2"
      #   enfant: "child"
      # DEMANDEUR: "Applicant"
      # IDENTITE: "Identity"
      # PRESENT: "Present at the time of application"
      # SEXE: "Sex"
      # PHOTO: "Shot"
      # INFORMATIONS_NAISSANCE: "Birth informations"
      # VILLE_NAISSANCE: "Place of birth (town)"
      # PAYS_NAISSANCE: "Place of birth (country)"
      # NOM_PERE: "Family name of father"
      # PRENOM_PERE: "Given name of father"
      # NOM_MERE: "Family name of mother"
      # PRENOM_MERE: "Given name of mother"
      # PROFIL_DEMANDE_MINEUR: "Demand profile"
      # NOM_REPRESENTANT_LEGAL: "Name of the legal representative"
      # PRENOM_REPRESENTANT_LEGAL: "First name of the legal representative"
      # PERSONNE_MORALE: "Legal representative, moral person"
      # DESIGNATION_PERSONNE_MORALE: "Designation of the legal person"
      # INFORMATIONS_COMPLEMENTAIRES: "Further information"
      # SITUATION_FAMILIALE: "Family situation"
      # LANGUE_OFPRA: "Hearing language to OFPRA"
      # TELEPHONE: "Phone number"
      # EMAIL: "Email"
      # ENFANT_USAGER_1: "Child of the user 1"
      # ENFANT_USAGER_2: "Child of the user 2"
      # ADRESSE: "Address"
      # ADRESSE_INCONNUE: "Address unknown"
      # COMPLEMENT: "Additional"
      # CODE_INSEE: "Insee code"
      # PAYS: "Country"
